export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_LOADING = 'USER_AUTH_LOADING';
export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT';

export const MESSAGE_LOADING = 'MESSAGE_LOADING';
export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS';
export const MESSAGE_RESET = 'MESSAGE_RESET';
